### ISSUE TITLE
An API error occurred: notNull Violation: ExportJob.sourceType cannot be null  Error ID: undefined

### ISSUE THREAD

**Issue by aaronlwan** [redivis/datastudio-connector#1]
Hi!

The connector was working perfectly fine for me on Data Studio for the past few months, but now, I'm getting this error when trying to connect Redivis with Data Studio:

"An API error occurred: notNull Violation: ExportJob.sourceType cannot be null 

Error ID: undefined"

Could anyone help me resolve this issue? What does this error mean?

**Comment by imathews** [comment]
@aaronlwan thanks so much for reporting this. This was a bug on our end due to a recent regression, and should now be resolved.
